apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pihole.fullname" . }}-password
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  password: {{ .Values.adminPassword | b64enc }}
